[package]
name = "bedrock"
version = "1.0.0"
edition = "2021"

[features]
default = ["settings", "telemetry"]

settings = ["bedrock-macros", "serde", "serde_yaml", "yaml-merge-keys", "serde_path_to_error"]
telemetry = ["bedrock-macros", "telemetry-log"]

telemetry-log = ["slog", "slog-async", "slog-json", "slog-term"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
anyhow = { workspace = true }
bedrock-macros = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_path_to_error = { workspace = true, optional = true }
serde_yaml = { workspace = true, optional = true }
slog = { workspace = true, optional = true }
slog-async = { workspace = true, optional = true }
slog-json = { workspace = true, optional = true }
slog-term = { workspace = true, optional = true }
yaml-merge-keys = { workspace = true, optional = true }

[dev-dependencies]
rusty-hook = { workspace = true }
