[workspace]
members = [
    "bedrock",
    "bedrock-macros",
]
resolver = "2"

[profile.release]
debug = 1

[workspace.dependencies]
anyhow = { version = "1" }
bedrock = { version = "1", path = "./bedrock" }
bedrock-macros = { version = "1", path = "./bedrock-macros" }
darling = "0.14"
proc-macro2 = { version = "1", default-features = false }
rusty-hook = "0.11"
quote = "1"
syn = { version = "1", features = ["full", "fold", "parsing", "extra-traits"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_yaml = "0.8"
serde_path_to_error = "0.1"
slog = { version = "2.4", features = ["max_level_trace"] }
slog-async = "2.3"
slog-json = "2.3"
slog-term = "2.4"
yaml-merge-keys = { version = "0.5", features = ["serde_yaml"] }