[workspace]
members = [
    "bedrock",
    "bedrock-macros",
    "tools/gen-syscall-enum"
]
resolver = "2"

[workspace.package]
version = "1.2.0"
repository = "https://bitbucket.cfdata.org/projects/OXY/repos/bedrock"
publish = ["cloudflare"]
edition = "2021"

[workspace.metadata.release]
pre-release-commit-message = "Release {{version}}"
shared-version = true
tag-prefix = ""
publish = false

[profile.release]
debug = 1

[workspace.dependencies]
anyhow = { version = "1", features = ["backtrace", "std"] }
bedrock = { version = "1", path = "./bedrock", registry = "cloudflare" }
bedrock-macros = { version = "1", path = "./bedrock-macros", registry = "cloudflare" }
bindgen = { version = "0.65", default-features = false, features = ["runtime"] }
cc = "1.0"
crossbeam-channel = "0.5"
darling = "0.14"
erased-serde = "0.3.28"
futures-util = "0.3.28"
hyper = { version = "0.14.27", default-features = false, features = ["http1", "runtime", "server"] }
indexmap = { version = "2.0.0", features = ["serde"] }
once_cell = "1.5"
parking_lot = "0.12"
proc-macro2 = { version = "1", default-features = false }
prometheus = { version = "0.13.3", features = ["process"] }
prometheus-client = "0.18.1"
prometools = { version = "0.2.1", features = ["serde"] }
rand = "0.8"
rusty-hook = "0.11"
rustracing = "0.6"
rustracing_jaeger = "0.9"
quote = "1"
regex = "1.8"
routerify = "3"
socket2 = { version = "0.5.3", features = ["all"] }
syn = { version = "1", features = ["full", "fold", "parsing", "extra-traits"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_path_to_error = "0.1"
serde_yaml = "0.8"
serde_with = "2.3.1"
slog = { version = "2.4", features = ["max_level_trace"] }
slog-async = "2.3"
slog-json = "2.3"
slog-term = "2.4"
tempfile = "3.7"
tokio = { version = "1.2", features = ["full"] }
thread_local = "1.1"
tikv-jemallocator = { version = "0.5", features = ["profiling", "stats", "background_threads"] }
tikv-jemalloc-ctl = { version = "0.5", features = ["use_std"]}
yaml-merge-keys = { version = "0.5", features = ["serde_yaml"] }
