[workspace]
members = [
    "bedrock",
    "bedrock-macros",
    "tools/gen-syscall-enum"
]
resolver = "2"

[profile.release]
debug = 1

[workspace.dependencies]
anyhow = { version = "1", features = ["backtrace", "std"] }
bedrock = { version = "1", path = "./bedrock", registry = "cloudflare" }
bedrock-macros = { version = "1", path = "./bedrock-macros", registry = "cloudflare" }
bindgen = "0.65"
cc = "1.0"
crossbeam-channel = "0.5"
darling = "0.14"
once_cell = "1.5"
parking_lot = "0.12"
proc-macro2 = { version = "1", default-features = false }
rand = "0.8"
rusty-hook = "0.11"
rustracing = "0.6"
rustracing_jaeger = "0.9"
quote = "1"
regex = "1.8"
syn = { version = "1", features = ["full", "fold", "parsing", "extra-traits"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_yaml = "0.8"
serde_path_to_error = "0.1"
slog = { version = "2.4", features = ["max_level_trace"] }
slog-async = "2.3"
slog-json = "2.3"
slog-term = "2.4"
tokio = { version = "1.24", features = ["full"] }
thread_local = "1.1"
yaml-merge-keys = { version = "0.5", features = ["serde_yaml"] }
