[package]
name = "bedrock-macros"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
bedrock = { workspace = true }