[package]
name = "examples"
version = "1.0.0"
publish = false
edition = "2021"

[dev-dependencies]
anyhow = { workspace = true }
bedrock = { workspace = true }
futures-util = { workspace = true }
hyper = { workspace = true }
tokio = { workspace = true }

[[example]]
name = "http_server"
path = "http_server/main.rs"
